/**
 * Commentary Agent — Post-processor
 *
 * Fills missing required fields in the Commentary output schema by reading
 * from the tool-run history (primarily fetch_data_matrix) and deal context.
 *
 * The Commentary model occasionally omits required fields like entity_name,
 * summary, confidence_score, or jedi_score due to LLM nondeterminism. This
 * postProcess ensures the final object always satisfies the strict Zod schema
 * before validation, mirroring the Cashflow postProcess pattern.
 */

import { query } from '../database/connection';
import { logger } from '../utils/logger';
import type { RunContext } from './runtime/types';

/** Shape of the summary returned by fetch_data_matrix tool result payload */
interface MatrixSummary {
  dealName?: string;
  location?: string;
  keyMetrics?: {
    units?: number;
    yearBuilt?: number;
    occupancy?: number;
    avgRent?: number;
  };
}

export async function commentaryPostProcess(
  rawOutput: Record<string, unknown>,
  ctx: RunContext,
  runId: string,
): Promise<Record<string, unknown>> {
  const output = { ...rawOutput };

  try {
    // ── Step 1: Extract deal metadata from fetch_data_matrix tool results ─
    let matrixData: MatrixSummary | null = null;
    let dealName = '';
    let dealLocation = '';
    let occupancy = 0;
    let avgRent = 0;
    try {
      const { rows } = await query(
        `SELECT payload
         FROM agent_run_steps
         WHERE agent_run_id = $1 AND step_type = 'tool_result' AND tool_name = 'fetch_data_matrix'
         ORDER BY step_index ASC
         LIMIT 1`,
        [runId]
      );
      if (rows.length > 0) {
        const payload = typeof rows[0].payload === 'string'
          ? JSON.parse(rows[0].payload)
          : rows[0].payload;
        // payload is { context: {...}, summary: { dealName, keyMetrics: {...}, ... } }
        if (payload?.summary && typeof payload.summary === 'object') {
          matrixData = payload.summary as MatrixSummary;
          dealName = matrixData.dealName ?? '';
          dealLocation = matrixData.location ?? '';
          occupancy = matrixData.keyMetrics?.occupancy ?? 0;
          avgRent = matrixData.keyMetrics?.avgRent ?? 0;
        }
      }
    } catch (err: any) {
      logger.warn('[CommentaryPostProcess] Failed to read fetch_data_matrix result', { error: err.message });
    }

    // ── Step 2: Fill entity metadata ────────────────────────────────────
    if (!output.entity_type || output.entity_type === '') {
      output.entity_type = 'deal';
    }
    if (!output.entity_id || output.entity_id === '') {
      output.entity_id = ctx.dealId ?? 'unknown';
    }
    if (!output.entity_name || output.entity_name === '') {
      output.entity_name = dealName || (ctx.dealId ? `Deal ${ctx.dealId.slice(0, 8)}` : 'Unknown Entity');
    }

    // ── Step 3: Fill narrative sections from model output or synthesize ──
    if (!output.market_narrative || typeof output.market_narrative !== 'object') {
      output.market_narrative = {
        title: 'Market Overview',
        content: 'Market analysis generated by Commentary Agent.',
        sentiment: 'neutral',
      };
    }
    // Ensure market_narrative has all required subfields
    const mn = output.market_narrative as Record<string, unknown>;
    if (!mn.title) mn.title = 'Market Overview';
    if (!mn.content) mn.content = `Market analysis for ${String(output.entity_name ?? 'property')}.`;
    if (!mn.sentiment) mn.sentiment = 'neutral';

    // ── Step 4: Fill investment_thesis ──────────────────────────────────
    if (!output.investment_thesis || typeof output.investment_thesis !== 'object') {
      output.investment_thesis = {
        recommendation: 'Hold',
        points: [
          { icon: 'Minus', color: 'amber', text: 'Insufficient data for detailed thesis — review manually' },
        ],
      };
    }
    const it = output.investment_thesis as Record<string, unknown>;
    if (!it.recommendation) it.recommendation = 'Hold';
    if (!Array.isArray(it.points) || it.points.length === 0) {
      it.points = [
        { icon: 'Minus', color: 'amber', text: 'Insufficient data for detailed thesis — review manually' },
      ];
    }

    // ── Step 5: Fill supply_narrative ───────────────────────────────────
    if (!output.supply_narrative || typeof output.supply_narrative !== 'object') {
      output.supply_narrative = {
        title: 'Supply Dynamics',
        content: 'Supply analysis included in market narrative.',
        sentiment: 'neutral',
      };
    }
    const sn = output.supply_narrative as Record<string, unknown>;
    if (!sn.title) sn.title = 'Supply Dynamics';
    if (!sn.content) sn.content = 'Supply analysis included in market narrative.';
    if (!sn.sentiment) sn.sentiment = 'neutral';

    // ── Step 6: Fill scalar fields ──────────────────────────────────────
    if (!output.recommended_strategy || output.recommended_strategy === '') {
      output.recommended_strategy = 'Stabilize and Hold';
    }
    if (typeof output.jedi_score !== 'number' || isNaN(output.jedi_score as number)) {
      // Try to derive from data matrix signals
      if (occupancy > 0) {
        const occScore = Math.min(100, Math.round(occupancy * 100));
        output.jedi_score = Math.round(occScore * 0.6 + 30);
      } else {
        output.jedi_score = 50; // neutral baseline
      }
    }
    if (typeof output.arbitrage_flag !== 'boolean') {
      output.arbitrage_flag = false;
    }
    if (typeof output.arbitrage_delta !== 'number' || isNaN(output.arbitrage_delta as number)) {
      output.arbitrage_delta = 0;
    }
    if (!output.summary || output.summary === '') {
      const entityName = String(output.entity_name ?? 'Property');
      output.summary = `${entityName} analysis complete. JEDI Score: ${String(output.jedi_score)}`;
    }
    if (typeof output.confidence_score !== 'number' || isNaN(output.confidence_score as number)) {
      output.confidence_score = 0.5; // moderate default
    }
    if (!output.completed_at) {
      output.completed_at = new Date().toISOString();
    }

    // ── Step 7: Ensure citations is an array ────────────────────────────
    if (!Array.isArray(output.citations)) {
      output.citations = [];
    }

  } catch (err) {
    const errInfo = err instanceof Error
      ? { message: err.message, stack: err.stack?.split('\n').slice(0, 3).join('; ') }
      : { raw: String(err) };
    logger.error('[CommentaryPostProcess] Error during aggregation, falling back to raw output', { errInfo });
  }

  return output;
}
