/**
 * concessions.ts
 *
 * Core type definitions for the Concession Amortization Engine.
 * All downstream services import from here — never from individual engine files.
 *
 * ARCHITECTURAL RULES (§14 of CONCESSION_AMORTIZATION_SPEC):
 *
 *   EARNED-VS-RECOGNIZED-DISTINCTION:
 *     "Earned" concessions = cash committed at lease signing (ConcessionRecord.cash_value).
 *     "Recognized" concessions = dollars spread across P&L periods by this engine.
 *     These are NEVER the same value in the same period. Never mix labels or share a row.
 *
 *   CASH-INVARIANT-ACROSS-TREATMENTS:
 *     The total cash outflow is identical regardless of treatment (OPERATING / CAPITALIZED / HYBRID).
 *     Only the P&L presentation differs. The engine asserts this at runtime and throws on mismatch.
 *
 *   AMORTIZATION-METHOD-IS-PER-CONCESSION:
 *     Each ConcessionRecord carries its own AmortizationMethod. A single lease may carry
 *     multiple records (e.g. FREE_RENT + GIFT_CARD), each amortized independently.
 */

/** Six concession types the platform recognizes. */
export type ConcessionType =
  | 'FREE_RENT'
  | 'REDUCED_RENT'
  | 'MOVE_IN_SPECIAL'
  | 'GIFT_CARD'
  | 'WAIVED_FEE'
  | 'OTHER';

/**
 * Five amortization methods. One per ConcessionRecord.
 *
 *   STRAIGHT_LINE_GAAP    — equal monthly slices over the lease term (ASC 842 default)
 *   CASH_AT_COMMENCEMENT  — 100% recognized in the lease-start month
 *   BURN_OFF              — hyperbolic front-load: month k gets weight (n-k+1)/Σ(1..n)
 *   FRONT_LOADED          — platform default curve (12-month), scaled to actual term
 *   CUSTOM                — caller-supplied schedule via ConcessionRecord.custom_schedule
 */
export type AmortizationMethod =
  | 'STRAIGHT_LINE_GAAP'
  | 'CASH_AT_COMMENCEMENT'
  | 'BURN_OFF'
  | 'FRONT_LOADED'
  | 'CUSTOM';

/** Treatment applied to leasing costs — mirrors lease-velocity-types.ts */
export type LeasingCostTreatment = 'OPERATING' | 'CAPITALIZED' | 'HYBRID';

/**
 * A single concession committed at lease signing.
 * One lease may carry multiple ConcessionRecord entries (AMORTIZATION-METHOD-IS-PER-CONCESSION).
 */
export interface ConcessionRecord {
  /** Unique concession id (uuid) */
  id: string;
  /** Parent deal */
  deal_id: string;
  /** Lease this concession is attached to */
  lease_id: string;
  /** Category of concession */
  concession_type: ConcessionType;
  /**
   * Total cash dollar amount committed at signing. Always positive.
   * This is the "EARNED" figure — never displayed as recognized in the same period.
   */
  cash_value: number;
  /** ISO date the lease commences (YYYY-MM-DD) */
  lease_start_date: string;
  /** ISO date the lease expires (YYYY-MM-DD) */
  lease_end_date: string;
  /** Derived term length in months (inclusive of start + end month) */
  lease_term_months: number;
  /** How this concession's cash_value is spread across P&L periods */
  amortization_method: AmortizationMethod;
  /**
   * Caller-supplied monthly schedule.
   * Required when amortization_method === 'CUSTOM'; ignored otherwise.
   * Entries must sum to cash_value (within $0.01 rounding).
   * month format: YYYYMM
   */
  custom_schedule?: Array<{ month: string; amount: number }>;
  /**
   * True when this concession was incurred during the property's lease-up period.
   * Under CAPITALIZED treatment, is_lease_up_period=true records are stripped from
   * P&L recognition and routed to AmortizationOutput.lease_up_reserve_required.
   */
  is_lease_up_period: boolean;
  /** Treatment in effect when this record was generated by the LV engine. */
  leasing_cost_treatment: LeasingCostTreatment;
  /**
   * If the lease terminated early, the ISO date of termination.
   * The engine writes off the remaining unamortized balance in the termination month.
   * §7.1 — mutually exclusive with structural_write_off_date; if both are set,
   * the earlier date governs.
   */
  early_termination_date?: string | null;
  /**
   * §7.8 — Structural write-off date: when a deal-level event (sale, foreclosure,
   * partnership dissolution) forces all unamortized concession balances off the books.
   * Engine writes off remaining balance in this month with reason='structural'.
   * Applied AFTER early_termination_date if both are set (only one write-off fires).
   */
  structural_write_off_date?: string | null;
  /** True when the concession was for a renewal (vs. new lease) */
  is_renewal: boolean;
  /**
   * True when this record originates from subject property historical data
   * (i.e. the recognition period may have started in the past).
   * The engine still amortizes from lease_start_date; months in the past are retained
   * in the schedule so trailing totals reconcile correctly.
   */
  is_subject_history: boolean;
  /**
   * §7.9 / §12.9 no-concession-field inference flag.
   * True when cash_value was inferred from rent roll / LV engine data rather than
   * explicitly provided. Engine processes the record normally; this flag is informational
   * for upstream callers to know the origin of cash_value. Records where inference
   * failed (cash_value === 0 and inferred_from_rent_roll === true) are skipped by
   * the orchestrator with a console.warn — not thrown, to avoid blocking other records.
   */
  inferred_from_rent_roll?: boolean;
  /**
   * Fiscal year start month (1=Jan … 12=Dec). Inherited from deal settings.
   * Defaults to 1 when absent. Used by aggregateByFiscalYear.
   */
  fiscal_year_start_month?: number;
}

/** A single month of recognized concession expense */
export interface MonthlyRecognitionEntry {
  /** YYYYMM e.g. "202501" */
  month: string;
  /** Recognized dollars in this period */
  amount: number;
}

/** An amortization write-off event */
export interface WriteOff {
  concession_id: string;
  lease_id: string;
  /** YYYYMM of the period the write-off hits P&L */
  write_off_month: string;
  /** Dollar amount written off */
  amount: number;
  /** Why the write-off occurred */
  reason: 'early_termination' | 'structural' | 'cross_horizon_truncation';
}

/** Per-concession amortization schedule produced by the engine */
export interface ConcessionAmortizationSchedule {
  concession_id: string;
  lease_id: string;
  method: AmortizationMethod;
  treatment: LeasingCostTreatment;
  /** True → record was routed to lease_up_reserve_required rather than P&L */
  is_lease_up_period: boolean;
  /** Ordered monthly recognition entries */
  monthly_entries: MonthlyRecognitionEntry[];
  /** Write-offs generated for this concession (early termination, structural) */
  write_offs: WriteOff[];
  /**
   * Dollars that would have been recognized beyond the analysis horizon.
   * Tracked for cash-invariant reconciliation; NOT included in monthly_recognition.
   */
  truncated_recognition_post_horizon: number;
}

/** Full engine output returned by amortizeConcessions() */
export interface AmortizationOutput {
  /** One schedule per input ConcessionRecord */
  schedules: ConcessionAmortizationSchedule[];
  /**
   * Aggregated monthly P&L recognition (OPERATING + HYBRID treatment records).
   * Key: YYYYMM, Value: dollars recognized.
   * CAPITALIZED lease-up records are excluded here — they appear in lease_up_reserve_required.
   */
  monthly_recognition: Record<string, number>;
  /** Calendar year totals derived from monthly_recognition. Key: YYYY */
  calendar_year_recognition: Record<string, number>;
  /** Fiscal year totals derived from monthly_recognition. Key: YYYY (fiscal year label) */
  fiscal_year_recognition: Record<string, number>;
  /**
   * Total dollars routed to the lease-up reserve (S&U) rather than P&L.
   * Only populated when leasing_cost_treatment=CAPITALIZED and is_lease_up_period=true.
   */
  lease_up_reserve_required: number;
  /** All write-offs across all concession records */
  write_offs: WriteOff[];
  /** Write-offs falling within the current calendar year (year-to-date) */
  write_offs_year_to_date: number;
  /** ISO timestamp when this output was computed */
  computed_at: string;
}

/** Input envelope for amortizeConcessions() */
export interface AmortizationEngineInput {
  /** All concession records to process */
  records: ConcessionRecord[];
  /**
   * Maximum months to project forward from current_date.
   * Recognition beyond this horizon is tracked as truncated_recognition_post_horizon.
   * Defaults to 120.
   */
  horizon_months?: number;
  /**
   * Reference date for horizon calculations and year-to-date write-off logic.
   * Format: YYYY-MM-DD. Defaults to today.
   */
  current_date?: string;
  /**
   * Fiscal year start month (1=Jan … 12=Dec).
   * Applied uniformly across all records. Defaults to 1.
   */
  fiscal_year_start_month?: number;
  /** Treatment to apply when routing lease-up-period records */
  leasing_cost_treatment: LeasingCostTreatment;
}

/**
 * dealContext.concession_recognition shape — cached in deal context
 * and recomputed on: LV engine output update, leasing_cost_treatment change,
 * subject_history update, fiscal_year_start_month change.
 */
export interface DealConcessionRecognition {
  /** Per-month recognized dollars. Key: YYYYMM */
  monthly: Record<string, number>;
  /** Calendar year totals. Key: YYYY string */
  by_calendar_year: Record<string, number>;
  /** Fiscal year totals. Key: YYYY string (fiscal year label) */
  by_fiscal_year: Record<string, number>;
  /** Write-off dollars recognized in the current calendar year */
  write_offs_year_to_date: number;
  /** ISO timestamp of last engine run */
  last_recomputed: string;
}
