/**
 * generate-property-descriptions-sql.ts
 *
 * Reads ARCHIVE_ENRICH_STATE.json and generates INSERT SQL for
 * property_descriptions table. Pipe into Replit DB.
 *
 * Usage:
 *   npx ts-node --transpile-only scripts/generate-property-descriptions-sql.ts > seed_pd.sql
 *   # copy to Replit and run:
 *   psql $DATABASE_URL < seed_pd.sql
 */

import * as fs from 'fs';
import * as path from 'path';

interface EnrichStateProperties {
  [parcelId: string]: {
    status: string;
    address?: string;
    addressCity?: string;
    addressState?: string;
    addressZip?: string;
    confidence?: string;
    source?: string;
    yearBuilt?: number;
    unitCount?: number;
    class?: string;
    data?: Array<{ field: string; value: string }>;
  };
}

interface EnrichState {
  properties: EnrichStateProperties;
}

const statePath = path.resolve(__dirname, '..', 'docs', 'operations', 'ARCHIVE_ENRICH_STATE.json');

if (!fs.existsSync(statePath)) {
  console.error('State file not found at:', statePath);
  process.exit(1);
}

const state: EnrichState = JSON.parse(fs.readFileSync(statePath, 'utf-8'));
const properties = state.properties;
const parcelIds = Object.keys(properties);

console.log(`-- Generated by generate-property-descriptions-sql.ts`);
console.log(`-- ${parcelIds.length} properties`);
console.log(``);

let total = 0;

for (const parcelId of parcelIds) {
  const prop = properties[parcelId];
  const now = new Date().toISOString();

  // Build the property_descriptions INSERT
  // parcel_id is the PK, other fields are JSONB (LayeredValue)

  const yearBuilt = prop.yearBuilt;
  const unitCount = prop.unitCount;
  const propClass = prop.class;

  // Build address from data array or props
  let address: { street?: string; city?: string; state?: string; zip?: string } | null = null;
  let city: string | null = prop.addressCity || null;
  let stateCode: string | null = prop.addressState || null;
  let zip: string | null = prop.addressZip || null;

  if (prop.address) {
    address = { street: prop.address, city: city || undefined, state: stateCode || undefined, zip: zip || undefined };
  }

  const msa = null; // Could derive from city+state later

  const cols: string[] = ['parcel_id'];
  const vals: string[] = [];

  const esc = (v: string) => `'${v.replace(/'/g, "''")}'`;

  vals.push(esc(parcelId));

  // property_name
  const propertyName = parcelId; // Use parcelId as placeholder name
  cols.push('property_name');
  const propertyNameJsonb = {
    resolved: propertyName,
    layers: {
      om: { value: propertyName, source_file_id: null, confidence: 0.5, extracted_at: now },
    },
    resolution_rule: 'highest_confidence',
  };
  vals.push(esc(JSON.stringify(propertyNameJsonb)));

  // address
  if (address) {
    cols.push('address');
    vals.push(esc(JSON.stringify({
      resolved: address,
      layers: { 
        om: { value: address, source_file_id: null, confidence: 0.5, extracted_at: now, source: 'om_extraction' },
      },
      resolution_rule: 'highest_confidence',
    })));
  }

  // year_built
  if (yearBuilt) {
    cols.push('year_built');
    vals.push(esc(JSON.stringify({
      resolved: yearBuilt,
      layers: {
        om: { value: yearBuilt, source_file_id: null, confidence: 0.7, extracted_at: now, source: 'om_extraction' },
      },
      resolution_rule: 'highest_confidence',
    })));
  }

  // unit_count
  if (unitCount) {
    cols.push('unit_count');
    vals.push(esc(JSON.stringify({
      resolved: unitCount,
      layers: {
        om: { value: unitCount, source_file_id: null, confidence: 0.7, extracted_at: now, source: 'om_extraction' },
      },
      resolution_rule: 'highest_confidence',
    })));
  }

  // asset_class
  if (propClass) {
    cols.push('asset_class');
    vals.push(esc(JSON.stringify({
      resolved: propClass,
      layers: {
        web: { value: propClass, source_url: '', fetched_at: now },
      },
      resolution_rule: 'highest_confidence',
    })));
  }

  // created_at, updated_at
  cols.push('created_at');
  vals.push(esc(now));
  cols.push('updated_at');
  vals.push(esc(now));

  const insertSql = `INSERT INTO property_descriptions (${cols.join(', ')}) VALUES (${vals.map((_, i) => `$${i + 1}`).join(', ')}) ON CONFLICT (parcel_id) DO UPDATE SET ${cols.filter(c => c !== 'parcel_id').map(c => `${c} = EXCLUDED.${c}`).join(', ')};`;

  console.log(insertSql);
  total++;

  if (total % 50 === 0) {
    console.log(`-- ${total}/${parcelIds.length}`);
  }
}

console.log('');
console.log(`-- Total: ${total} properties`);
