CREATE TABLE IF NOT EXISTS deal_zoning_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  deal_id UUID NOT NULL UNIQUE REFERENCES deals(id) ON DELETE CASCADE,
  base_district_code VARCHAR(50),
  base_district_id UUID,
  municipality VARCHAR(100),
  state VARCHAR(50),
  residential_far DECIMAL(10,4),
  nonresidential_far DECIMAL(10,4),
  combined_far DECIMAL(10,4),
  applied_far DECIMAL(10,4),
  density_method VARCHAR(20) DEFAULT 'units_per_acre',
  max_density_per_acre DECIMAL(10,2),
  max_height_ft INTEGER,
  max_stories INTEGER,
  height_buffer_ft INTEGER,
  height_beyond_buffer_ft INTEGER,
  max_lot_coverage_pct DECIMAL(5,2),
  setback_front_ft INTEGER,
  setback_side_ft INTEGER,
  setback_rear_ft INTEGER,
  min_parking_per_unit DECIMAL(5,2),
  open_space_pct DECIMAL(5,2),
  lot_area_sf DECIMAL(12,2),
  buildable_area_sf DECIMAL(12,2),
  centroid_lng DECIMAL(12,8),
  centroid_lat DECIMAL(12,8),
  overlays JSONB DEFAULT '[]'::jsonb,
  conditional_ordinance_text TEXT,
  conditional_overrides JSONB DEFAULT '{}'::jsonb,
  user_overrides JSONB DEFAULT '{}'::jsonb,
  constraint_source VARCHAR(20) DEFAULT 'auto',
  resolution_errors JSONB DEFAULT '[]'::jsonb,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_deal_zoning_profiles_deal_id ON deal_zoning_profiles(deal_id);
