CREATE TABLE IF NOT EXISTS weekly_traffic_snapshots (
  id SERIAL PRIMARY KEY,
  deal_id VARCHAR(255) NOT NULL,
  property_name VARCHAR(255),
  week_ending DATE NOT NULL,
  total_units INTEGER,
  traffic INTEGER,
  in_person_tours INTEGER,
  website_leads INTEGER,
  apps INTEGER,
  cancellations INTEGER,
  denials INTEGER,
  net_leases INTEGER,
  closing_ratio DECIMAL(5,4),
  beg_occ INTEGER,
  move_ins INTEGER,
  move_outs INTEGER,
  transfers INTEGER,
  end_occ INTEGER,
  vacant_model INTEGER,
  vacant_rented INTEGER,
  vacant_unrented INTEGER,
  vacant_total INTEGER,
  notice_rented INTEGER,
  notice_unrented INTEGER,
  notice_total INTEGER,
  avail_1br INTEGER,
  avail_2br INTEGER,
  avail_3br INTEGER,
  occ_pct DECIMAL(5,4),
  leased_pct DECIMAL(5,4),
  avail_pct DECIMAL(5,4),
  source VARCHAR(50) DEFAULT 'upload',
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(deal_id, week_ending)
);

CREATE INDEX IF NOT EXISTS idx_weekly_traffic_deal_id ON weekly_traffic_snapshots(deal_id);
CREATE INDEX IF NOT EXISTS idx_weekly_traffic_week ON weekly_traffic_snapshots(deal_id, week_ending);
