ALTER TABLE deals ADD COLUMN IF NOT EXISTS project_type VARCHAR(20) NOT NULL DEFAULT 'existing';
ALTER TABLE deals ALTER COLUMN project_type SET DEFAULT 'existing';
ALTER TABLE deals ALTER COLUMN project_type SET NOT NULL;
