-- Agent System Tables
-- Full autonomous agent infrastructure
-- Created: 2026-04-22

-- ============================================================================
-- AGENT CONVERSATIONS
-- Stores all conversations between users and agents
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id TEXT NOT NULL,
  deal_id UUID REFERENCES deals(id) ON DELETE SET NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  agent_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  skills_used JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_conv_conversation ON agent_conversations(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_conv_user ON agent_conversations(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_conv_deal ON agent_conversations(deal_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_conv_agent ON agent_conversations(agent_id, created_at DESC);

COMMENT ON TABLE agent_conversations IS 'Stores conversation history between users and AI agents';
COMMENT ON COLUMN agent_conversations.agent_id IS 'ID of the agent persona (e.g., cfo, legal, orchestrator)';
COMMENT ON COLUMN agent_conversations.skills_used IS 'Array of skill IDs used in this message';

-- ============================================================================
-- AGENT NOTIFICATIONS
-- Notifications generated by agents for users
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  deal_id UUID REFERENCES deals(id) ON DELETE SET NULL,
  agent_id TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('info', 'warning', 'alert', 'action_required')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  channels JSONB NOT NULL DEFAULT '["in_app"]',
  action_url TEXT,
  read_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_notif_user ON agent_notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_notif_unread ON agent_notifications(user_id) WHERE read_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_agent_notif_deal ON agent_notifications(deal_id, created_at DESC);

COMMENT ON TABLE agent_notifications IS 'Notifications generated by agents for user attention';
COMMENT ON COLUMN agent_notifications.type IS 'Severity: info, warning, alert, action_required';
COMMENT ON COLUMN agent_notifications.channels IS 'Delivery channels: in_app, email, slack, webhook';

-- ============================================================================
-- AGENT EVENTS
-- Log of all events that trigger agent workflows
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type TEXT NOT NULL,
  deal_id UUID REFERENCES deals(id) ON DELETE SET NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  payload JSONB NOT NULL DEFAULT '{}',
  processed_at TIMESTAMPTZ,
  agents_triggered TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_events_type ON agent_events(event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_events_deal ON agent_events(deal_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_events_unprocessed ON agent_events(created_at) WHERE processed_at IS NULL;

COMMENT ON TABLE agent_events IS 'Log of platform events that trigger agent workflows';
COMMENT ON COLUMN agent_events.event_type IS 'Event type (document_uploaded, email_received, etc.)';
COMMENT ON COLUMN agent_events.agents_triggered IS 'Array of agent IDs that processed this event';

-- ============================================================================
-- AGENT WORKFLOW RUNS
-- Tracks autonomous agent workflow executions
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_workflow_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id TEXT NOT NULL,
  event_id UUID REFERENCES agent_events(id) ON DELETE SET NULL,
  deal_id UUID REFERENCES deals(id) ON DELETE SET NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  trigger_event TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  skills_executed JSONB DEFAULT '[]',
  result JSONB,
  error TEXT,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_runs_agent ON agent_workflow_runs(agent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_deal ON agent_workflow_runs(deal_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_status ON agent_workflow_runs(status) WHERE status IN ('pending', 'running');

COMMENT ON TABLE agent_workflow_runs IS 'Tracks individual agent workflow executions';

-- ============================================================================
-- AGENT SCHEDULES
-- User-specific agent schedule configurations
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_schedules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  agent_id TEXT NOT NULL,
  schedule_type TEXT NOT NULL CHECK (schedule_type IN ('daily', 'weekly', 'monthly', 'custom')),
  cron_expression TEXT,
  enabled BOOLEAN NOT NULL DEFAULT true,
  last_run_at TIMESTAMPTZ,
  next_run_at TIMESTAMPTZ,
  config JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  UNIQUE(user_id, agent_id, schedule_type)
);

CREATE INDEX IF NOT EXISTS idx_agent_schedules_user ON agent_schedules(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_schedules_next_run ON agent_schedules(next_run_at) WHERE enabled = true;

COMMENT ON TABLE agent_schedules IS 'User-specific agent schedule configurations';

-- ============================================================================
-- AGENT PREFERENCES
-- User preferences for agent behavior
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  agent_id TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  notification_channels JSONB DEFAULT '["in_app"]',
  auto_execute BOOLEAN DEFAULT false,
  priority_override INTEGER,
  custom_prompt TEXT,
  config JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  UNIQUE(user_id, agent_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_prefs_user ON agent_preferences(user_id);

COMMENT ON TABLE agent_preferences IS 'User-specific agent behavior preferences';

-- ============================================================================
-- ADD COLUMNS TO USER_PREFERENCES IF NEEDED
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'user_preferences' AND column_name = 'agent_notifications'
  ) THEN
    ALTER TABLE user_preferences ADD COLUMN agent_notifications BOOLEAN DEFAULT true;
  END IF;
END $$;
