// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/commentary-wireframes/InlineCards.tsx": () => import("../components/mockups/commentary-wireframes/InlineCards.tsx"),
  "./components/mockups/commentary-wireframes/MetricsEnhanced.tsx": () => import("../components/mockups/commentary-wireframes/MetricsEnhanced.tsx"),
  "./components/mockups/commentary-wireframes/SidePanel.tsx": () => import("../components/mockups/commentary-wireframes/SidePanel.tsx"),
  "./components/mockups/f3-comps-tab/CompsTab.tsx": () => import("../components/mockups/f3-comps-tab/CompsTab.tsx"),
  "./components/mockups/f3-demand-tab/DemandTab.tsx": () => import("../components/mockups/f3-demand-tab/DemandTab.tsx"),
  "./components/mockups/f3-discovery-tab/DiscoveryTab.tsx": () => import("../components/mockups/f3-discovery-tab/DiscoveryTab.tsx"),
  "./components/mockups/f3-trends-tab/TrendsTab.tsx": () => import("../components/mockups/f3-trends-tab/TrendsTab.tsx"),
  "./components/mockups/f3-program-tab/ProgramDev.tsx": () => import("../components/mockups/f3-program-tab/ProgramDev.tsx"),
  "./components/mockups/f3-program-tab/ProgramExisting.tsx": () => import("../components/mockups/f3-program-tab/ProgramExisting.tsx"),
  "./components/mockups/f3-program-tab/ProgramRedev.tsx": () => import("../components/mockups/f3-program-tab/ProgramRedev.tsx"),
  "./components/mockups/market-performance/Combined.tsx": () => import("../components/mockups/market-performance/Combined.tsx"),
  "./components/mockups/msa-overview/Overview.tsx": () => import("../components/mockups/msa-overview/Overview.tsx")
};
