import React from 'react';
export const Badge: React.FC<any> = ({ children, className, ...props }: any) => <div className={className} {...props}>{children}</div>;
export const BadgeContent: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeHeader: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeTitle: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeTrigger: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeList: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeValue: React.FC<any> = ({ children, ...props }: any) => <span {...props}>{children}</span>;
export const BadgeItem: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeProvider: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeRoot: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgePortal: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeOverlay: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeClose: React.FC<any> = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const BadgeDescription: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeFooter: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeTrack: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const BadgeRange: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export const BadgeThumb: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export default Badge;
