import React from 'react';
export const Button: React.FC<any> = ({ children, className, ...props }: any) => <div className={className} {...props}>{children}</div>;
export const ButtonContent: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonHeader: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonTitle: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonTrigger: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonList: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonValue: React.FC<any> = ({ children, ...props }: any) => <span {...props}>{children}</span>;
export const ButtonItem: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonProvider: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonRoot: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonPortal: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonOverlay: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonClose: React.FC<any> = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const ButtonDescription: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonFooter: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonTrack: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const ButtonRange: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export const ButtonThumb: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export default Button;
