import React from 'react';
export const Card: React.FC<any> = ({ children, className, ...props }: any) => <div className={className} {...props}>{children}</div>;
export const CardContent: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardHeader: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardTitle: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardTrigger: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardList: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardValue: React.FC<any> = ({ children, ...props }: any) => <span {...props}>{children}</span>;
export const CardItem: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardProvider: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardRoot: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardPortal: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardOverlay: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardClose: React.FC<any> = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const CardDescription: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardFooter: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardTrack: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const CardRange: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export const CardThumb: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export default Card;
