import React from 'react';
export const Dialog: React.FC<any> = ({ children, className, ...props }: any) => <div className={className} {...props}>{children}</div>;
export const DialogContent: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogHeader: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogTitle: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogTrigger: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogList: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogValue: React.FC<any> = ({ children, ...props }: any) => <span {...props}>{children}</span>;
export const DialogItem: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogProvider: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogRoot: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogPortal: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogOverlay: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogClose: React.FC<any> = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const DialogDescription: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogFooter: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogTrack: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const DialogRange: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export const DialogThumb: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export default Dialog;
