import React from 'react';
export const Input: React.FC<any> = ({ children, className, ...props }: any) => <div className={className} {...props}>{children}</div>;
export const InputContent: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputHeader: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputTitle: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputTrigger: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputList: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputValue: React.FC<any> = ({ children, ...props }: any) => <span {...props}>{children}</span>;
export const InputItem: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputProvider: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputRoot: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputPortal: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputOverlay: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputClose: React.FC<any> = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const InputDescription: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputFooter: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputTrack: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const InputRange: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export const InputThumb: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export default Input;
