import React from 'react';
export const Slider: React.FC<any> = ({ children, className, ...props }: any) => <div className={className} {...props}>{children}</div>;
export const SliderContent: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderHeader: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderTitle: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderTrigger: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderList: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderValue: React.FC<any> = ({ children, ...props }: any) => <span {...props}>{children}</span>;
export const SliderItem: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderProvider: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderRoot: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderPortal: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderOverlay: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderClose: React.FC<any> = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const SliderDescription: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderFooter: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderTrack: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const SliderRange: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export const SliderThumb: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export default Slider;
