import React from 'react';
export const Tabs: React.FC<any> = ({ children, className, ...props }: any) => <div className={className} {...props}>{children}</div>;
export const TabsContent: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsHeader: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsTitle: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsTrigger: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsList: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsValue: React.FC<any> = ({ children, ...props }: any) => <span {...props}>{children}</span>;
export const TabsItem: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsProvider: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsRoot: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsPortal: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsOverlay: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsClose: React.FC<any> = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const TabsDescription: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsFooter: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsTrack: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TabsRange: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export const TabsThumb: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export default Tabs;
