import React from 'react';
export const Tooltip: React.FC<any> = ({ children, className, ...props }: any) => <div className={className} {...props}>{children}</div>;
export const TooltipContent: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipHeader: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipTitle: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipTrigger: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipList: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipValue: React.FC<any> = ({ children, ...props }: any) => <span {...props}>{children}</span>;
export const TooltipItem: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipProvider: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipRoot: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipPortal: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipOverlay: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipClose: React.FC<any> = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const TooltipDescription: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipFooter: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipTrack: React.FC<any> = ({ children, ...props }: any) => <div {...props}>{children}</div>;
export const TooltipRange: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export const TooltipThumb: React.FC<any> = ({ ...props }: any) => <div {...props} />;
export default Tooltip;
