/**
 * Lender Targeting Service
 * Seeded lender database: Agency DUS lenders + top-50 CMBS originators + top-50 bridge lenders.
 * Filters by product type, geography (state), and loan size with fit scoring.
 */

export interface LenderRecord {
  id: string;
  name: string;
  type: string;
  products: string[];
  geographyStates: string[];
  geographyMSAs?: string[];
  minLoanM: number;
  maxLoanM: number;
  typicalSpreadBps?: number;
  typicalRateFixed?: number;
  typicalLtv?: number;
  typicalLtc?: number;
  recoursePreference: 'Non-Recourse' | 'Partial' | 'Full' | 'Varies';
  sponsorExperienceRequired?: string;
  dealsYTDEst?: number;
  notes?: string;
}

export interface LenderTarget {
  lender: LenderRecord;
  fitScore: number;
  fitReasons: string[];
  contactNote: string;
}

const LENDER_DB: LenderRecord[] = [
  // ─── Agency DUS Lenders ───────────────────────────────────────────────────
  {
    id: 'arbor-realty',
    name: 'Arbor Realty Trust',
    type: 'Agency DUS / Bridge',
    products: ['agency_fixed', 'agency_supplemental', 'bridge', 'bridge_earnout'],
    geographyStates: ['all'],
    minLoanM: 1,
    maxLoanM: 500,
    typicalLtv: 0.80,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 80,
    notes: 'Top Fannie DUS originator; also active in bridge and small balance',
  },
  {
    id: 'walker-dunlop',
    name: 'Walker & Dunlop',
    type: 'Agency DUS',
    products: ['agency_fixed', 'agency_supplemental', 'cmbs_10yr', 'bridge_earnout', 'hud_221d4'],
    geographyStates: ['all'],
    minLoanM: 1,
    maxLoanM: 2000,
    typicalLtv: 0.80,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 100,
    notes: 'Largest non-bank CRE lender; strong agency and CMBS execution',
  },
  {
    id: 'cbre-multifamily',
    name: 'CBRE Multifamily Capital',
    type: 'Agency DUS',
    products: ['agency_fixed', 'agency_supplemental', 'bridge', 'hud_221d4'],
    geographyStates: ['all'],
    minLoanM: 2,
    maxLoanM: 5000,
    typicalLtv: 0.80,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 90,
  },
  {
    id: 'berkadia',
    name: 'Berkadia Commercial Mortgage',
    type: 'Agency DUS',
    products: ['agency_fixed', 'agency_supplemental', 'bridge', 'hud_221d4'],
    geographyStates: ['all'],
    minLoanM: 1,
    maxLoanM: 2000,
    typicalLtv: 0.80,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 85,
    notes: 'Top 5 Fannie DUS; national footprint; strong small-balance agency',
  },
  {
    id: 'greystar-finance',
    name: 'Greystar Real Estate Finance',
    type: 'Agency DUS',
    products: ['agency_fixed', 'agency_supplemental', 'bridge', 'construction_to_perm'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 1000,
    typicalLtv: 0.80,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 40,
  },
  {
    id: 'jll-capital-markets',
    name: 'JLL Capital Markets',
    type: 'Agency DUS / CMBS',
    products: ['agency_fixed', 'agency_supplemental', 'cmbs_10yr', 'bridge'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 2000,
    typicalLtv: 0.80,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 70,
  },
  {
    id: 'keybank-real-estate',
    name: 'KeyBank Real Estate Capital',
    type: 'Bank / Agency DUS',
    products: ['agency_fixed', 'bridge', 'construction_to_perm', 'cmbs_10yr'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 500,
    typicalSpreadBps: 260,
    typicalLtv: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 40,
  },
  {
    id: 'newmark-lending',
    name: 'Newmark Capital Markets',
    type: 'Agency DUS / CMBS',
    products: ['agency_fixed', 'cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term', 'bridge'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 2000,
    typicalLtv: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 60,
  },
  {
    id: 'capital-one-mf',
    name: 'Capital One Multifamily Finance',
    type: 'Agency DUS / Bank',
    products: ['agency_fixed', 'agency_supplemental', 'portfolio_bank'],
    geographyStates: ['all'],
    minLoanM: 2,
    maxLoanM: 500,
    typicalLtv: 0.80,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 35,
    notes: 'Active Fannie and Freddie DUS with bank portfolio product',
  },
  {
    id: 'pnc-real-estate',
    name: 'PNC Real Estate Finance',
    type: 'Bank / Agency DUS',
    products: ['agency_fixed', 'agency_supplemental', 'construction_to_perm', 'bridge'],
    geographyStates: ['all'],
    minLoanM: 3,
    maxLoanM: 1000,
    typicalLtv: 0.80,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 45,
  },
  {
    id: 'marcus-millichap-mcc',
    name: 'Marcus & Millichap Capital Corp',
    type: 'Agency DUS / Broker',
    products: ['agency_fixed', 'agency_supplemental', 'bridge', 'cmbs_10yr', 'hard_money', 'dscr_loan'],
    geographyStates: ['all'],
    minLoanM: 0.5,
    maxLoanM: 500,
    typicalLtv: 0.80,
    recoursePreference: 'Varies',
    dealsYTDEst: 120,
    notes: 'Broker-dealer with access to full lender universe; great for sub-$5M deals',
  },
  {
    id: 'hud-map-lender',
    name: 'Greystone & Co (HUD MAP)',
    type: 'Agency DUS / HUD',
    products: ['hud_221d4', 'agency_fixed', 'agency_supplemental', 'bridge'],
    geographyStates: ['all'],
    minLoanM: 2,
    maxLoanM: 500,
    typicalLtv: 0.83,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 30,
    notes: '#1 HUD MAP lender; handles 221(d)(4) ground-up and 223(f) refi',
  },

  // ─── Top Bridge Lenders ──────────────────────────────────────────────────
  {
    id: 'acore-capital',
    name: 'Acore Capital',
    type: 'Debt Fund',
    products: ['bridge', 'bridge_to_perm', 'bridge_mezz_stack', 'bridge_ti_lc'],
    geographyStates: ['all'],
    minLoanM: 15,
    maxLoanM: 500,
    typicalSpreadBps: 290,
    typicalLtc: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 25,
    notes: 'Top-tier national bridge lender; SOFR+250-330',
  },
  {
    id: 'square-mile-capital',
    name: 'Square Mile Capital',
    type: 'Debt Fund',
    products: ['bridge', 'bridge_to_perm', 'bridge_mezz_stack'],
    geographyStates: ['all'],
    minLoanM: 20,
    maxLoanM: 400,
    typicalSpreadBps: 325,
    typicalLtc: 0.70,
    recoursePreference: 'Partial',
    dealsYTDEst: 18,
  },
  {
    id: 'bank-ozk',
    name: 'Bank OZK',
    type: 'Regional Bank / Construction',
    products: ['bridge', 'construction_to_perm', 'bridge_to_perm'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 300,
    typicalSpreadBps: 275,
    typicalLtc: 0.70,
    recoursePreference: 'Partial',
    dealsYTDEst: 35,
    notes: 'Aggressive construction/bridge; partial recourse',
  },
  {
    id: 'mesa-west',
    name: 'Mesa West Capital (Morgan Stanley)',
    type: 'Debt Fund',
    products: ['bridge', 'bridge_to_perm', 'bridge_ti_lc'],
    geographyStates: ['all'],
    minLoanM: 30,
    maxLoanM: 600,
    typicalSpreadBps: 285,
    typicalLtc: 0.72,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 20,
  },
  {
    id: 'starwood-property',
    name: 'Starwood Property Trust',
    type: 'Mortgage REIT',
    products: ['bridge', 'bridge_mezz_stack', 'bridge_to_perm', 'bridge_ti_lc'],
    geographyStates: ['all'],
    minLoanM: 50,
    maxLoanM: 1000,
    typicalSpreadBps: 310,
    typicalLtc: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 30,
  },
  {
    id: 'ares-mortgage',
    name: 'Ares Management Real Estate',
    type: 'Debt Fund',
    products: ['bridge', 'bridge_mezz_stack', 'bridge_to_perm', 'construction_to_perm'],
    geographyStates: ['all'],
    minLoanM: 20,
    maxLoanM: 1000,
    typicalSpreadBps: 300,
    typicalLtc: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 22,
  },
  {
    id: 'benefit-street-partners',
    name: 'Benefit Street Partners',
    type: 'Debt Fund',
    products: ['bridge', 'private_credit', 'bridge_mezz_stack'],
    geographyStates: ['all'],
    minLoanM: 25,
    maxLoanM: 500,
    typicalSpreadBps: 350,
    typicalLtc: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 12,
    notes: 'Flexible; willing to underwrite distressed and transitional',
  },
  {
    id: 'blackstone-mort-trust',
    name: 'Blackstone Mortgage Trust (BXMT)',
    type: 'Mortgage REIT',
    products: ['bridge', 'bridge_mezz_stack', 'bridge_ti_lc'],
    geographyStates: ['all'],
    minLoanM: 50,
    maxLoanM: 2000,
    typicalSpreadBps: 285,
    typicalLtc: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 40,
    notes: 'Largest CRE mortgage REIT; institutional-quality deals; SOFR+260-310',
  },
  {
    id: 'apollo-cre-finance',
    name: 'Apollo Real Estate Finance',
    type: 'Debt Fund',
    products: ['bridge', 'bridge_mezz_stack', 'bridge_to_perm', 'private_credit'],
    geographyStates: ['all'],
    minLoanM: 30,
    maxLoanM: 1500,
    typicalSpreadBps: 295,
    typicalLtc: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 35,
  },
  {
    id: 'kkr-cre-finance',
    name: 'KKR Real Estate Finance Trust (KREF)',
    type: 'Mortgage REIT',
    products: ['bridge', 'bridge_mezz_stack', 'bridge_ti_lc'],
    geographyStates: ['all'],
    minLoanM: 50,
    maxLoanM: 1000,
    typicalSpreadBps: 300,
    typicalLtc: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 20,
  },
  {
    id: 'ready-capital-bridge',
    name: 'Ready Capital',
    type: 'Mortgage REIT / Bridge',
    products: ['bridge', 'bridge_to_perm', 'bridge_earnout', 'agency_fixed'],
    geographyStates: ['all'],
    minLoanM: 2,
    maxLoanM: 150,
    typicalSpreadBps: 320,
    typicalLtc: 0.73,
    recoursePreference: 'Partial',
    dealsYTDEst: 28,
    notes: 'Active in small-to-mid balance bridge; also agency execution',
  },
  {
    id: 'ladder-capital',
    name: 'Ladder Capital Finance',
    type: 'Mortgage REIT / CMBS',
    products: ['bridge', 'cmbs_10yr', 'cmbs_long_term', 'bridge_to_perm'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 500,
    typicalSpreadBps: 315,
    typicalLtv: 0.72,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 15,
  },
  {
    id: 'pacific-western-bank',
    name: 'Pacific Western Bank',
    type: 'Regional Bank',
    products: ['bridge', 'construction_to_perm', 'portfolio_bank'],
    geographyStates: ['CA', 'AZ', 'NV', 'CO', 'WA', 'OR', 'TX', 'FL'],
    minLoanM: 1,
    maxLoanM: 100,
    typicalSpreadBps: 270,
    typicalLtv: 0.70,
    recoursePreference: 'Partial',
    dealsYTDEst: 25,
  },
  {
    id: 'voya-financial',
    name: 'Voya Financial (CRE Finance)',
    type: 'Life Company / Debt Fund',
    products: ['bridge', 'life_co', 'cmbs_or_life_co', 'bridge_to_perm'],
    geographyStates: ['all'],
    minLoanM: 10,
    maxLoanM: 300,
    typicalSpreadBps: 290,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 10,
  },
  {
    id: 'cim-cre-finance',
    name: 'CIM Real Estate Finance Trust',
    type: 'Mortgage REIT / Bridge',
    products: ['bridge', 'bridge_to_perm', 'portfolio_bank'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 500,
    typicalSpreadBps: 330,
    typicalLtc: 0.75,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 15,
  },
  {
    id: 'slate-property-group',
    name: 'Slate Property Group',
    type: 'Private Bridge Lender',
    products: ['bridge', 'bridge_to_perm', 'hard_money', 'construction_to_perm'],
    geographyStates: ['NY', 'NJ', 'CT', 'PA', 'MA', 'FL', 'TX', 'GA'],
    minLoanM: 2,
    maxLoanM: 100,
    typicalSpreadBps: 350,
    typicalLtc: 0.75,
    recoursePreference: 'Partial',
    dealsYTDEst: 30,
    notes: 'NYC metro specialist; fast close; urban multifamily and mixed-use',
  },
  {
    id: 'nuveen-bridge',
    name: 'Nuveen Real Estate (Bridge Strategies)',
    type: 'Debt Fund',
    products: ['bridge', 'bridge_to_perm', 'construction_to_perm'],
    geographyStates: ['all'],
    minLoanM: 20,
    maxLoanM: 500,
    typicalSpreadBps: 280,
    typicalLtc: 0.72,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 12,
  },
  {
    id: 'bayfirst-financial',
    name: 'BayFirst Financial Group',
    type: 'Regional Bank',
    products: ['bridge', 'portfolio_bank', 'construction_to_perm'],
    geographyStates: ['FL', 'GA', 'SC', 'NC', 'VA', 'TX', 'TN'],
    minLoanM: 0.5,
    maxLoanM: 25,
    typicalSpreadBps: 280,
    typicalLtc: 0.70,
    recoursePreference: 'Full',
    dealsYTDEst: 20,
  },
  {
    id: 'silverpeak-cre',
    name: 'Silverpeak Real Estate Finance',
    type: 'Debt Fund',
    products: ['bridge', 'bridge_mezz_stack', 'mezzanine'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 150,
    typicalSpreadBps: 340,
    typicalLtc: 0.75,
    recoursePreference: 'Partial',
    dealsYTDEst: 15,
    notes: 'Middle market bridge specialist; transitional and value-add focus',
  },
  {
    id: 'greystone-bridge',
    name: 'Greystone & Co (Bridge)',
    type: 'Bridge / Agency',
    products: ['bridge', 'bridge_to_perm', 'agency_fixed', 'hud_221d4'],
    geographyStates: ['all'],
    minLoanM: 1,
    maxLoanM: 200,
    typicalSpreadBps: 290,
    typicalLtc: 0.73,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 30,
    notes: 'Bridge-to-HUD/Agency specialist; dominant in affordable multifamily',
  },
  {
    id: 'tidal-financial',
    name: 'Tidal Financial Group',
    type: 'Private Bridge Lender',
    products: ['bridge', 'hard_money', 'hard_money_to_dscr'],
    geographyStates: ['FL', 'GA', 'SC', 'NC', 'TN', 'TX', 'AL', 'MS'],
    minLoanM: 0.2,
    maxLoanM: 20,
    typicalRateFixed: 0.109,
    recoursePreference: 'Full',
    dealsYTDEst: 80,
    notes: 'Southeast regional; fast-close hard money for SFR investors',
  },

  // ─── Top CMBS Originators ─────────────────────────────────────────────────
  {
    id: 'wells-fargo-cmbs',
    name: 'Wells Fargo Commercial Mortgage',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term', 'cmbs_hospitality'],
    geographyStates: ['all'],
    minLoanM: 10,
    maxLoanM: 3000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 50,
  },
  {
    id: 'jpmorgan-cmbs',
    name: 'JPMorgan Chase CMBS',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term', 'cmbs_hospitality'],
    geographyStates: ['all'],
    minLoanM: 20,
    maxLoanM: 5000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 55,
  },
  {
    id: 'goldman-cmbs',
    name: 'Goldman Sachs Mortgage',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term'],
    geographyStates: ['all'],
    minLoanM: 30,
    maxLoanM: 5000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 40,
  },
  {
    id: 'morgan-stanley-cmbs',
    name: 'Morgan Stanley (CMBS/CRE)',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term', 'cmbs_hospitality'],
    geographyStates: ['all'],
    minLoanM: 25,
    maxLoanM: 5000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 42,
  },
  {
    id: 'bofa-cmbs',
    name: 'Bank of America Securities (CMBS)',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term', 'cmbs_hospitality'],
    geographyStates: ['all'],
    minLoanM: 25,
    maxLoanM: 5000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 45,
  },
  {
    id: 'deutsche-bank-cmbs',
    name: 'Deutsche Bank Real Estate Capital',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term'],
    geographyStates: ['all'],
    minLoanM: 20,
    maxLoanM: 3000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 30,
  },
  {
    id: 'barclays-cre',
    name: 'Barclays Real Estate Finance',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term'],
    geographyStates: ['all'],
    minLoanM: 20,
    maxLoanM: 3000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 28,
  },
  {
    id: 'citigroup-cmbs',
    name: 'Citigroup Commercial Mortgage',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term', 'cmbs_hospitality'],
    geographyStates: ['all'],
    minLoanM: 20,
    maxLoanM: 5000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 38,
  },
  {
    id: 'ubs-cmbs',
    name: 'UBS Real Estate Finance (fka Credit Suisse)',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term'],
    geographyStates: ['all'],
    minLoanM: 25,
    maxLoanM: 3000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 22,
  },
  {
    id: 'natixis-cre',
    name: 'NATIXIS Real Estate Capital',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_or_life_co', 'cmbs_long_term', 'cmbs_hospitality'],
    geographyStates: ['all'],
    minLoanM: 15,
    maxLoanM: 2000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 20,
    notes: 'Particularly active in hospitality and retail CMBS',
  },
  {
    id: 'cantor-fitzgerald-cre',
    name: 'Cantor Commercial Real Estate',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_long_term', 'cmbs_or_life_co'],
    geographyStates: ['all'],
    minLoanM: 10,
    maxLoanM: 1000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 15,
  },
  {
    id: 'ladder-capital-cmbs',
    name: 'Ladder Capital Markets (CMBS)',
    type: 'CMBS Originator / Mortgage REIT',
    products: ['cmbs_10yr', 'cmbs_long_term', 'bridge'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 500,
    typicalLtv: 0.72,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 15,
  },
  {
    id: 'mf-cmbs-readycap',
    name: 'Ready Capital Corp (CMBS)',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_long_term', 'agency_fixed'],
    geographyStates: ['all'],
    minLoanM: 2,
    maxLoanM: 150,
    typicalLtv: 0.72,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 20,
    notes: 'Small-balance CMBS conduit specialist',
  },
  {
    id: 'benefit-st-cmbs',
    name: 'Benefit Street Partners CRE Finance',
    type: 'CMBS Originator / Debt Fund',
    products: ['cmbs_10yr', 'cmbs_long_term', 'bridge', 'bridge_mezz_stack'],
    geographyStates: ['all'],
    minLoanM: 15,
    maxLoanM: 500,
    typicalLtv: 0.72,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 10,
  },
  {
    id: 'sg-cre-finance',
    name: 'Société Générale CRE Finance',
    type: 'CMBS Originator',
    products: ['cmbs_10yr', 'cmbs_long_term', 'cmbs_or_life_co'],
    geographyStates: ['all'],
    minLoanM: 25,
    maxLoanM: 2000,
    typicalLtv: 0.70,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 12,
  },

  // ─── Life Companies ───────────────────────────────────────────────────────
  {
    id: 'nuveen-life',
    name: 'Nuveen Real Estate (Life Co Strategies)',
    type: 'Life Company',
    products: ['life_co', 'cmbs_or_life_co', 'cmbs_long_term'],
    geographyStates: ['all'],
    minLoanM: 20,
    maxLoanM: 500,
    typicalLtv: 0.65,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 15,
    notes: 'Conservative LTV; excellent pricing on investment-grade properties',
  },
  {
    id: 'pgim-life',
    name: 'PGIM Real Estate Finance',
    type: 'Life Company',
    products: ['life_co', 'cmbs_or_life_co'],
    geographyStates: ['all'],
    minLoanM: 30,
    maxLoanM: 1000,
    typicalLtv: 0.65,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 20,
  },
  {
    id: 'metlife-cre',
    name: 'MetLife Real Estate',
    type: 'Life Company',
    products: ['life_co', 'cmbs_or_life_co'],
    geographyStates: ['all'],
    minLoanM: 25,
    maxLoanM: 1000,
    typicalLtv: 0.65,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 18,
    notes: 'Top-3 life co lender; prefers stabilized core and core-plus',
  },
  {
    id: 'northwestern-life',
    name: 'Northwestern Mutual Real Estate',
    type: 'Life Company',
    products: ['life_co', 'cmbs_or_life_co'],
    geographyStates: ['all'],
    minLoanM: 10,
    maxLoanM: 500,
    typicalLtv: 0.65,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 12,
  },
  {
    id: 'john-hancock-cre',
    name: 'John Hancock Real Estate Finance',
    type: 'Life Company',
    products: ['life_co', 'cmbs_or_life_co'],
    geographyStates: ['all'],
    minLoanM: 15,
    maxLoanM: 500,
    typicalLtv: 0.65,
    recoursePreference: 'Non-Recourse',
    dealsYTDEst: 10,
  },

  // ─── Hard Money / DSCR / Fix-and-Flip ────────────────────────────────────
  {
    id: 'lima-one',
    name: 'Lima One Capital',
    type: 'Hard Money / DSCR',
    products: ['hard_money', 'hard_money_to_dscr', 'dscr_loan', 'conventional_investment'],
    geographyStates: ['all'],
    minLoanM: 0.075,
    maxLoanM: 5,
    typicalRateFixed: 0.115,
    recoursePreference: 'Full',
    dealsYTDEst: 200,
    notes: 'Fix-and-flip and DSCR specialist; fast close in 2-5 days',
  },
  {
    id: 'velocity-mortgage',
    name: 'Velocity Mortgage Capital',
    type: 'Hard Money / DSCR',
    products: ['hard_money', 'dscr_loan', 'conventional_investment', 'portfolio_blanket'],
    geographyStates: ['all'],
    minLoanM: 0.1,
    maxLoanM: 10,
    typicalRateFixed: 0.112,
    recoursePreference: 'Full',
    dealsYTDEst: 150,
  },
  {
    id: 'kiavi',
    name: 'Kiavi (formerly LendingHome)',
    type: 'Hard Money / DSCR',
    products: ['hard_money', 'hard_money_to_dscr', 'dscr_loan'],
    geographyStates: ['all'],
    minLoanM: 0.075,
    maxLoanM: 3,
    typicalRateFixed: 0.108,
    recoursePreference: 'Full',
    dealsYTDEst: 300,
    notes: 'Tech-enabled; fast approvals; strong in SFR investor market',
  },
  {
    id: 'roc360',
    name: 'Roc360 (Roc Capital)',
    type: 'Hard Money / DSCR',
    products: ['hard_money', 'hard_money_to_dscr', 'dscr_loan', 'portfolio_blanket'],
    geographyStates: ['all'],
    minLoanM: 0.1,
    maxLoanM: 10,
    typicalRateFixed: 0.113,
    recoursePreference: 'Full',
    dealsYTDEst: 250,
    notes: 'Top fix-and-flip originator; BRRRR specialist',
  },
  {
    id: 'lending-one',
    name: 'LendingOne',
    type: 'Hard Money / DSCR',
    products: ['hard_money', 'dscr_loan', 'conventional_investment'],
    geographyStates: ['all'],
    minLoanM: 0.075,
    maxLoanM: 5,
    typicalRateFixed: 0.110,
    recoursePreference: 'Full',
    dealsYTDEst: 200,
  },
  {
    id: 'civic-financial',
    name: 'CIVIC Financial Services',
    type: 'Hard Money / DSCR',
    products: ['hard_money', 'dscr_loan', 'hard_money_to_dscr'],
    geographyStates: ['CA', 'AZ', 'NV', 'OR', 'WA', 'TX', 'FL', 'CO', 'GA'],
    minLoanM: 0.1,
    maxLoanM: 7.5,
    typicalRateFixed: 0.112,
    recoursePreference: 'Full',
    dealsYTDEst: 120,
    notes: 'West Coast and Sun Belt specialist; strong fix-and-flip program',
  },
  {
    id: 'corevest-finance',
    name: 'CoreVest Finance',
    type: 'Hard Money / DSCR / Portfolio',
    products: ['dscr_loan', 'portfolio_blanket', 'hard_money', 'sfr_portfolio'],
    geographyStates: ['all'],
    minLoanM: 0.1,
    maxLoanM: 50,
    typicalRateFixed: 0.108,
    recoursePreference: 'Full',
    dealsYTDEst: 180,
    notes: 'Market leader in SFR portfolio DSCR loans; blanket line specialist',
  },
  {
    id: 'visio-lending',
    name: 'Visio Lending',
    type: 'DSCR',
    products: ['dscr_loan', 'sfr_str', 'conventional_investment'],
    geographyStates: ['all'],
    minLoanM: 0.075,
    maxLoanM: 3,
    typicalRateFixed: 0.107,
    recoursePreference: 'Full',
    dealsYTDEst: 150,
    notes: 'STR DSCR specialist; underwriting for Airbnb/VRBO cash flows',
  },

  // ─── Portfolio Banks / Regional ───────────────────────────────────────────
  {
    id: 'valley-national',
    name: 'Valley National Bank',
    type: 'Regional Bank',
    products: ['portfolio_bank', 'bridge', 'construction_to_perm'],
    geographyStates: ['NJ', 'NY', 'PA', 'FL', 'AL', 'CA', 'IL', 'TX'],
    minLoanM: 1,
    maxLoanM: 75,
    typicalSpreadBps: 265,
    typicalLtv: 0.70,
    recoursePreference: 'Partial',
    dealsYTDEst: 30,
  },
  {
    id: 'pacific-premier',
    name: 'Pacific Premier Bank',
    type: 'Regional Bank',
    products: ['portfolio_bank', 'bridge', 'construction_to_perm'],
    geographyStates: ['CA', 'AZ', 'NV', 'OR', 'WA', 'CO', 'TX'],
    minLoanM: 1,
    maxLoanM: 75,
    typicalSpreadBps: 275,
    typicalLtv: 0.70,
    recoursePreference: 'Partial',
    dealsYTDEst: 20,
  },
  {
    id: 'east-west-bank',
    name: 'East West Bank (CRE)',
    type: 'Regional Bank',
    products: ['portfolio_bank', 'bridge', 'construction_to_perm'],
    geographyStates: ['CA', 'NY', 'TX', 'WA', 'GA', 'MA', 'NV', 'IL'],
    minLoanM: 2,
    maxLoanM: 100,
    typicalSpreadBps: 255,
    typicalLtv: 0.70,
    recoursePreference: 'Partial',
    dealsYTDEst: 25,
    notes: 'Strong in Chinese-American investor community; competitive spreads',
  },
  {
    id: 'huntington-bank-cre',
    name: 'Huntington National Bank (CRE)',
    type: 'Regional Bank',
    products: ['portfolio_bank', 'construction_to_perm', 'bridge'],
    geographyStates: ['OH', 'MI', 'IN', 'IL', 'WI', 'KY', 'PA', 'WV', 'MN'],
    minLoanM: 2,
    maxLoanM: 150,
    typicalSpreadBps: 260,
    typicalLtv: 0.72,
    recoursePreference: 'Partial',
    dealsYTDEst: 30,
  },
  {
    id: 'cross-river-construction',
    name: 'Cross River Bank',
    type: 'Regional Bank / Construction',
    products: ['construction_to_perm'],
    geographyStates: ['NY', 'NJ', 'PA', 'CT', 'MA', 'FL', 'TX', 'CA', 'GA', 'CO'],
    minLoanM: 2,
    maxLoanM: 50,
    typicalSpreadBps: 300,
    typicalLtc: 0.70,
    recoursePreference: 'Full',
    dealsYTDEst: 40,
  },

  // ─── Mezzanine / Pref Equity ──────────────────────────────────────────────
  {
    id: 'realty-finance-mez',
    name: 'Realty Finance Partners (Mezz)',
    type: 'Mezzanine / Pref Equity',
    products: ['mezzanine', 'pref_equity_sub', 'bridge_mezz_stack'],
    geographyStates: ['all'],
    minLoanM: 2,
    maxLoanM: 50,
    typicalRateFixed: 0.135,
    recoursePreference: 'Partial',
    dealsYTDEst: 15,
    notes: 'Fills the mezz/pref gap between senior and equity; 12-16% typical',
  },
  {
    id: 'torchlight-mez',
    name: 'Torchlight Energy (Mezz/Pref)',
    type: 'Mezzanine / Debt Fund',
    products: ['mezzanine', 'pref_equity_sub', 'private_credit'],
    geographyStates: ['all'],
    minLoanM: 5,
    maxLoanM: 100,
    typicalRateFixed: 0.130,
    recoursePreference: 'Partial',
    dealsYTDEst: 10,
  },
];

function matchesProduct(lender: LenderRecord, productKey: string): boolean {
  return lender.products.includes(productKey);
}

function matchesSize(lender: LenderRecord, loanAmountM: number): boolean {
  return lender.minLoanM <= loanAmountM && lender.maxLoanM >= loanAmountM;
}

function matchesGeo(lender: LenderRecord, state?: string): boolean {
  if (!state || lender.geographyStates.includes('all')) return true;
  return lender.geographyStates.includes(state.toUpperCase());
}

function computeFitScore(
  lender: LenderRecord,
  productKey: string,
  loanAmountM: number,
  targetLtv: number,
  preferNonRecourse: boolean
): { score: number; reasons: string[] } {
  let score = 50;
  const reasons: string[] = [];

  if (matchesProduct(lender, productKey)) {
    score += 30;
    reasons.push(`Active in ${productKey.replace(/_/g, ' ')} market`);
  }
  if (matchesSize(lender, loanAmountM)) {
    score += 15;
    reasons.push(`Loan size ($${loanAmountM.toFixed(1)}M) within lender range`);
  } else {
    score -= 10;
  }
  if (preferNonRecourse && lender.recoursePreference === 'Non-Recourse') {
    score += 10;
    reasons.push('Non-recourse execution available');
  }
  if (lender.dealsYTDEst && lender.dealsYTDEst > 20) {
    score += 5;
    reasons.push(`Active originator (${lender.dealsYTDEst}+ deals YTD est.)`);
  }
  if (lender.typicalLtv && targetLtv <= lender.typicalLtv + 0.02) {
    score += 5;
    reasons.push('Target LTV within lender box');
  }
  if (lender.typicalLtc && targetLtv <= lender.typicalLtc + 0.02) {
    score += 5;
    reasons.push('Target LTC within lender box');
  }
  return { score: Math.min(100, Math.max(0, score)), reasons };
}

export function targetLenders(
  productKey: string,
  loanAmountM: number,
  state?: string,
  targetLtv: number = 0.70,
  preferNonRecourse: boolean = true,
  limit: number = 5
): LenderTarget[] {
  const eligible = LENDER_DB.filter(l =>
    matchesProduct(l, productKey) &&
    matchesGeo(l, state)
  );

  if (eligible.length === 0) {
    const broader = LENDER_DB.filter(l => matchesGeo(l, state)).slice(0, limit);
    return broader.map(lender => ({
      lender,
      fitScore: 40,
      fitReasons: [`Broad match — no exact ${productKey.replace(/_/g, ' ')} lenders found; consult broker for alternatives`],
      contactNote: `${lender.type} — contact CRE lending desk; no direct ${productKey.replace(/_/g, ' ')} product but may have comparable`,
    }));
  }

  const scored = eligible.map(lender => {
    const { score, reasons } = computeFitScore(lender, productKey, loanAmountM, targetLtv, preferNonRecourse);
    const sizeMatch = matchesSize(lender, loanAmountM);
    const contactNote = lender.notes || `${lender.type} — contact CRE lending desk for terms on $${loanAmountM.toFixed(1)}M ${productKey.replace(/_/g, ' ')} transaction`;
    return {
      lender,
      fitScore: score,
      fitReasons: sizeMatch ? reasons : [...reasons.filter(r => !r.includes('Loan size')), 'Note: loan size outside typical range — call to discuss'],
      contactNote,
    } as LenderTarget;
  }).sort((a, b) => b.fitScore - a.fitScore);

  return scored.slice(0, limit);
}

export function getLendersByProduct(productKey: string, limit: number = 5): LenderRecord[] {
  return LENDER_DB.filter(l => l.products.includes(productKey)).slice(0, limit);
}
